### ISSUE TITLE
Automated tests to ensure build is working

### ISSUE THREAD

**Issue by BelfordZ** [open-rpc/generator-client#113]
## Problem

We should have a more clear distinction between testing contexts. Further, the tests should catch issues that would otherwise result in a build that is horrifically broken being published. The goal is not to have perfect test coverage so that we never ship a single bug, cause we would be at this for a life time. The goal is to **never ship a version of this tool that doesn't work at all**.

## Solution
 I propose a list of testing steps, going in order of "Fail Fast As Possible" - The time it takes for each group of test to pass must be increasing.

### Linting
Linting will catch syntax errors and various small issues. It's the fastest type of test, and so we run this first.

We should not give warnings - only errors. If it's not worth being an error, then don't use the rule.

### Unit Tests
Unit tests mock out any type of IO, as well as dependent modules. Unit tests test individual exported methods to ensure that their interfaces are upheld, and that any logic that the function is implementing is **documented via a use case formatted unit test**.

Ex of good unit test case:
> it("returns null if you try to divide by zero", () => { ... })

Ex of bad unit test case
> ("it doesn't divide by zero", () => { ... });

### Integration Tests
Integration tests are the most intensive test, and will generally take much longer than the others. They should test this tool from end to end, using the filesystem and everything just as a user would.

Integration tests should accomplish the following main points.

#### Make a build
The integration tests should use the built code, and should not run via ts-jest, but rather as nodejs targeted javascript.

#### Generating clients from examples
Using `build/bin/cli.js`, run the generator against each of the examples found in [@open-rpc/examples](https://github.com/open-rpc/examples). Write each generated client to the `test/` directory.

#### Integration Testing the generated clients in each language
For each generated example client, we must ensure that each language's client is functioning as intended. To do this, we must start a [mock server](https://github.com/open-rpc/mock-server), and run the [language-specific integration test script](#language-specific-integration-tests).

1. `node_modules/.bin/open-rpc-mock-server -s { "openrpc": "1.0.0-rc1", ... } -p 6969`
2. `./test/${exampleName}/${language}/bin/test.integration.sh`. 

To make this work, we obviously need to add a file to each `templates/{language}/static/bin/` a `test.sh` script that would run tests in the particular language-specific way.

##### Language Specific Integration Tests
The generated client for each language should have a tests suite that is generated alongside it. This means that the language specific client implementation **MUST** make provisions to generate these tests. Since each language has its own tools for testing, each language implementation must have an integration test script that follows the naming convention:

`./test/${exampleName}/${language}/bin/test.integration.sh`.

Once the script is run, the language specific tests should test the following:
 - the client can be imported.
 - for each method in the client:
   - call it using [example pairing](https://github.com/open-rpc/spec#example-pairing-object) that are available.
   - ensure the resulting response matches the [example pairing result](https://github.com/open-rpc/spec#example-result).
   

## Changes to generator-client's package.json
1. This will add the following "scripts" to the root package.json:
```json
{
  "test": "jest --coverage",
  "test:unit": "jest ./src",
  "test:integration": "jest ./integration-tests"
}
```
2. Requires generating a 'test application' alongside each client, which will template the calls to each method, asserting the result is correct.

**Comment by BelfordZ** [comment]
Requesting feedback @shanejonas @meowsbits @zmitton @mersinvald @r8d8

**Comment by meowsbits** [comment]
For the language-client integration script `./test/${exampleName}/${language}/bin/test.integration.sh`
- this is a `#!/usr/bin/env bash` script?
  + compliant w/ bash >= v3?
  + parsing JSON in the script will be common work. should the tool for that remain agnostic (delegated to each script to either install or confirm/deny existence of deps... eg. `sed`, `awk`, `jq`, `jj`, `json`, or whatever), or should we settle a standard tool and make that available for the script as a part of the `node_modules` set?

- or this is a `#!/usr/bin/env node` script.. we can call using `node ./test/${exampleName}/${language}/bin/test.integration.(sh|js)`?

**Comment by BelfordZ** [comment]
IMO it could be either bash OR node script. node is already a dependency, but the original intent was that it would be a shell script, and that it would be a small one. 

Hopefully in most cases, the shell script is just something simple as
```bash
go test
```

**Comment by meowsbits** [comment]
oh i see -- so to usually just manage delegating the test logic back to the language client 

would it be expected that the script would be responsible for installing or versioning go?

**Comment by BelfordZ** [comment]
good question. At the moment, its setup as 'u better have these things installed or it wont work'

Once we get things a little more stable, the plan is to revisit the dockerization of things, so we can have docker be the only dep.

**Comment by BelfordZ** [comment]
couldnt hurt to put installers in there to start with, but the goal is to keep things as light as possible for as long as possible

**Comment by meowsbits** [comment]
yea, cool. and it kind of makes sense that if you don't have go installed, the test will fail because the client will fail because you can't run the client from source.. :joy_cat:

**Comment by BelfordZ** [comment]
TODO: Write a go compiler in TS


:trollface:

**Comment by meowsbits** [comment]
- [x] write a compiler from Go to JavaScript for running Go code in a browser https://github.com/gopherjs/gopherjs

**Comment by meowsbits** [comment]
the linting and unit test examples above seem to be in JS -- is there an idea to support that stuff also/either with the language-specific code side? like `gofmt` ?

**Comment by BelfordZ** [comment]
linting doesnt mention anything about JS, I mean to imply that each language would have its own linting

Unit tests, yeah maybe i should remove the test examples ?

**Comment by meowsbits** [comment]
ah yea, i mean like `./test/${exampleName}/${language}/bin/test.integration.sh.` is for language-specific integration tests... is there an idea to do `./test/${exampleName}/${language}/bin/test.lint.sh.`

**Comment by BelfordZ** [comment]
yeah I think the lint example you have makes sense. it would effectively be 
`{process}.{target}.sh` for everything, where in this case (testing), target goes to mean "which test group do you want to target"

**Comment by meowsbits** [comment]
yea. so "process-target" becomes a nice simple way of "paragraphing" the test suite (or other processes too).

**Comment by meowsbits** [comment]
although i'm wondering if instead of thinking about them as 'scripts' (ala process.target.sh), we can just think about them as "commands," so you can run anything that's available on the system and - just like you would in the script.sh - but without having to nest those commands in a file and have to deal with opinions about how that file gets interpreted.

```
{
  "test:lint": ['gofmt ./*.go', 'go vet ./*.go'],
  "test:unit": ["go test -v ./..."],
  "test:integration": ["jest ./integration-tests", "bats ./path/to/my-script-test.sh"]
}
```

**Comment by shanejonas** [comment]
should this be in bin?

**Comment by BelfordZ** [comment]
@meowsbits hehe, this resembles the package.json format nicely :)

However, the idea was to use .sh files because I thought it would be the least opinionated, least abstraction answer. That being said, I'm in no way positive that this way is better, so I will give it some thought.

Maybe you could give it a try, and make a WIP PR to demonstrate how it would change things?
