### ISSUE TITLE
Remove Jayson

### ISSUE THREAD

**Issue by BelfordZ** [open-rpc/generator-client#123]
**Describe the bug**
[Jayson](https://github.com/tedeh/jayson) is a complete piece of shit, and it's downright embarrassing that it's the current 'best' json-rpc lib on NPM. The maintainer is incompetent, and has demonstrated his inability to maintain the project. https://github.com/tedeh/jayson/issues/131

We need to build a new one so we can provide proper support for JSON-RPC.

**Comment by shanejonas** [comment]
this is one I've found that looks promising:
https://github.com/bigstepinc/jsonrpc-bidirectional
