### ISSUE TITLE
add a binary to build artifacts

### ISSUE THREAD

**Issue by shanejonas** [open-rpc/generator-client#132]
**Is your feature request related to a problem? Please describe.**
i’d like binary build for `generator-client` so that i can brew or apt-get or maybe even chocolatey install the generator client as an alternative to nodejs installed.

**Comment by shanejonas** [comment]
I tried a couple out and this was the one that worked the best for me:

https://github.com/nexe/nexe

**Comment by devonwesley** [comment]
Working on this:

Current progress:

- The binary, using the `nexe` tool spits out to be 161m
- The schema-utils-js seem to be the package making the build a bit bigger, particularly the packages called "quicktype" and "json-schema".

Solution:
- just going to keep looking into the packages, but it might not get better.
- Theres flags you can pass to `nexe` that will build nodejs with certain packages, but I don't think this is going to help. Alot of the packages use each other.

**Comment by shanejonas** [comment]
I tested with `generator-client` on my machine with `nexe` installed globally and it ended up at `38M`

![image](https://user-images.githubusercontent.com/364566/56826711-c7f58580-6811-11e9-98f5-13ebe4a900a0.png)


maybe it's the way `nexe` is included in the project? not sure

**Comment by devonwesley** [comment]
Yeah, Did the build @shanejonas way, and it was alot smaller. 

```
#!/usr/bin/env node

const { compile } = require('nexe');
const getVersion = require('./get-version');

const releasePath = './build/macos';
const artifactName = `openrpc-${getVersion}`;

compile({ 
  input: './bin/cli.js',
  output: `${releasePath}/${artifactName}`,
  name: artifactName,
})
.then(() => console.log(`Ready! ${artifactName}`));
```

This is the code I currently have inside of a script file with nexe installed as a dev dependency. 

Maybe thats bloating it for some reason.
