### ISSUE TITLE
Tests fail indeterminantly

### ISSUE THREAD

**Issue by BelfordZ** [open-rpc/generator-client#169]
**Describe the bug**
https://circleci.com/gh/open-rpc/generator-client/513?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by BelfordZ** [comment]
can you take this @mersinvald

**Comment by mersinvald** [comment]
@BelfordZ still relevant?

**Comment by BelfordZ** [comment]
haven't seen it happen. Closin!
