### ISSUE TITLE
clients get created in current directory

### ISSUE THREAD

**Issue by shanejonas** [open-rpc/generator-client#195]
**Describe the bug**
`outDir` is always `cwd` so clients get created in current directory.

**To Reproduce**
1. `open-rpc-generator-client -d https://raw.githubusercontent.com/etclabscore/ethereum-json-rpc-specification/master/openrpc.json`
1. `ls`
1. See `typescript` and `rust` in cwd

**Expected behavior**
it should take the `OpenRPC` document's `info.title` and use that, the same way it does [here](https://github.com/open-rpc/generator-client/blob/d3fe19d886c103374f55c690a9033f2cf47e9676/src/index.ts#L31) for the `Class` name for the generated client.

**Resources**
https://github.com/open-rpc/generator-client/blob/d3fe19d886c103374f55c690a9033f2cf47e9676/src/cli.ts#L27

**Comment by devonwesley** [comment]
Is it because the user doesn't pass it in? Do you need like a default.

**Comment by shanejonas** [comment]
we always set it to `cwd`, seems kind of weird not to create an intermediate directory, just dumping `typescript` dir to my `cwd` doesnt seem right.

thoughts @BelfordZ ?

**Comment by BelfordZ** [comment]
Suggested that we accept an option `-o, --output` that is the directory to output the clients to.
