### ISSUE TITLE
Generator exports client class awkwardly for TS/JS

### ISSUE THREAD

**Issue by zcstarr** [open-rpc/generator-client#217]
**Describe the bug**
When generating the TS client, the client class that's generated places the class name under 
```js
exports.default = ClientClassName;
```
This results in not being able to require the class from js properly
```js
// Will not work from js
// Will work from ts
const ClientClassName = require('client-class-name')
clientClassName = new ClientClassName({})
```
```js
// This works currently from js 
const ClientClassName = require('client-class-name').default;
clientClassName = new ClientClassName({})
```
**Expected behavior**
```js
const ClientClassName = require('client-class-name')
or alternatively 
const {ClientClassName} = require('client-class-name')  // I have a preference for this
```
should work from js.

I believe it has to do with the import export style used in TS, where the TS is transpiling an additional .default. to the classname.

**Comment by BelfordZ** [comment]
Agreed that the clients should support both. We just need to export the class, as well as export it as the default export.
