### ISSUE TITLE
Some thoughts on current unresolved but defs thoughtabout issues

### ISSUE THREAD

**Issue by BelfordZ** [open-rpc/generator-client#25]
1. whats the cli interface and why that and what does it produce
    - after you 'produce it', do you:
       - re-do it when you updated your schema file
       - or is there a diff command for updating the one you have
3. when you generate, does it also creates builds of each one, or just generate the code and then you go in and compile + deploy each one
4. does it provide a script to do this shit on aggregate for the diff languages it supports
5. does it generate each language into the same project
6. how do you specify what languages you want to generate clients for
    - should u just always generate them all?
8. how do u specify the configs for each language

**Comment by shanejonas** [comment]
i think a lot of these questions around configuration can be solved via x- extensions in the spec
