### ISSUE TITLE
Call error with generated client after using latest client-generator 1.11.0

### ISSUE THREAD

**Issue by bakon11** [open-rpc/generator-client#272]
**Describe the bug**
When using  client-generator 1.11.0, and then using the generated client in my react project. I get the following error when making a call.

```
index.js:126 Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not an object
 if (openRpcMethodValidationErrors instanceof schema_utils_js_1.MethodNotFoundError || openRpcMethodValidationErrors.length > 0) {
      return Promise.reject(openRpcMethodValidationErrors);
    }
```

**Expected behavior**
I was expecting a call to my back end to fetch extra data

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Browser [chrome, Firefox]
 - Version [latest]

### Console
![image](https://user-images.githubusercontent.com/50184793/64287674-f0129500-cf25-11e9-9479-2a15b94ca4bb.png)

### Breakpoint
![image](https://user-images.githubusercontent.com/50184793/64287686-fbfe5700-cf25-11e9-99d0-77dd2b402a3e.png)

**Comment by shanejonas** [comment]
Hit this today with @bakon11
