### ISSUE TITLE
Add Dependabot + badges 

### ISSUE THREAD

**Issue by BelfordZ** [open-rpc/generator-client#29]
Should be applied to all the OpenRPC repos

**Comment by meowsbits** [comment]
![screenshot_20190307_162246](https://user-images.githubusercontent.com/45600330/53993588-7116de00-40f5-11e9-9195-944c3153b6c8.png)

**Comment by meowsbits** [comment]
But I've added the rest.

![screenshot_20190307_162439](https://user-images.githubusercontent.com/45600330/53993635-973c7e00-40f5-11e9-9e11-c9519d9bda1f.png)

**Comment by meowsbits** [comment]
All badges look like this:

[![Dependabot badge](https://img.shields.io/badge/Dependabot-enabled-brightgreen.svg?logo=dependabot)](https://dependabot.com/)

There is [some fancier stuff Dependabot offers w/ compatibility scores](https://dependabot.com/blog/introducing-dependabot-compatibility-scores/), but stickin with KISS for now.

**Comment by meowsbits** [comment]
Btw, sorry bout fuckin up the repo names on some of those pr's. :crying_cat_face: :cherry_blossom: :hocho:
