### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: methodTypings.generateTypings is not a function

### ISSUE THREAD

**Issue by GeoSkyGPS** [open-rpc/generator-client#312]
**Describe the bug**
When using `npm run generator-client` from my project folder or using circleCI workflows to deploy I get the following error when generating a client.
```
(node:6008) UnhandledPromiseRejectionWarning: TypeError: methodTypings.generateTypings is not a function
```

**To Reproduce**
Create a nodeJS openRPC project
then execute `npm run generator-client`

**Expected behavior**
I expected a client to be generated

**Screenshots**
![image](https://user-images.githubusercontent.com/24231950/69558023-2aac2c80-0f6d-11ea-888c-9f5df077aa97.png)
![image](https://user-images.githubusercontent.com/24231950/69558064-3ac40c00-0f6d-11ea-9533-9ebfaee2a84d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 and through circleCI
 - Version 1.13.0

**Comment by GeoSkyGPS** [comment]
The issue is with latest package "@open-rpc/typings": "1.6.0" not client generator

**Comment by BelfordZ** [comment]
fixed
