### ISSUE TITLE
.gitignore not getting copied

### ISSUE THREAD

**Issue by shanejonas** [open-rpc/generator-client#59]
**Describe the bug**
for `js` client:
the `.gitignore` folder is not getting copied to the newly generated client

**To Reproduce**
1. `open-rpc-generator-client -s https://raw.githubusercontent.com/etclabscore/multi-geth/0718d25e92e568f486be17123e9384ce15d8b48c/openrpc.json EthClient`
2. check contents of `EthClient/` folder for `.gitignore`
3. See that its missing

**Expected behavior**
I expect it to be there since its in the `static` folder for the `js` client.

**Comment by BelfordZ** [comment]
bumpity bumpbump

**Comment by BelfordZ** [comment]
https://github.com/open-rpc/generator-client/blob/master/src/index.ts#L52
fixed
