### ISSUE TITLE
Apache 2.0 License or a License of some kind.

### ISSUE THREAD

**Issue by stevanlohja** [open-rpc/generator-client#94]
**Is your feature request related to a problem? Please describe.**
Currently this repo does not have license. I'd like to recommend Apache 2.0 License. This idea came about when writing readme, usually license is the footer of such documentation and knowing the license status is better than not. If no License than License should be UnLicensed.

**Describe the solution you'd like**
When I land on the repo, I want to understand what the License is by discovering the License document in the code or reference in the Readme.

**Describe alternatives you've considered**
If no License than repo should state Unlicensed.

**Comment by shanejonas** [comment]
agreed. maybe a new ticket that is `pristine this repo`, will get us **Pristine** which gets us Apache 2 license and contributor files, all that stuff.

**Comment by shanejonas** [comment]
I just made this one on the `docs-react` repo: https://github.com/open-rpc/docs-react/issues/13
